package CodeList;

public interface AllowanceChargeReasonCode {
    String groupName();
    String code();
    String getReason();

    public enum Allowance implements AllowanceChargeReasonCode {
        _1("1", "Handling commission"),
        _2("2", "Amendment commission"),
        _3("3", "Acceptance commission"),
        _4("4", "Commission for obtaining acceptance"),
        _5("5", "Commission on delivery"),
        _6("6", "Advising commission"),
        _7("7", "Confirmation commission"),
        _8("8", " Deferred payment commission"),
        _9("9", "Commission for taking up documents"),
        _10("10", "Opening commission"),
        _11("11", "Fee for payment under reserve"),
        _12("12", "Discrepancy fee"),
        _13("13", "Domicilation commission"),
        _14("14", "Commission for release of goods"),
        _15("15", "Collection commission"),
        _16("16", "Negotiation commission"),
        _17("17", "Return commission"),
        _18("18", "B/L splitting charges"),
        _19("19", "Trust commission"),
        _20("20", "Transfer commission"),
        _21("21", "Commission for opening irrevocable documentary credits"),
        _22("22", "Pre-advice commission"),
        _23("23", "Supervisory commission"),
        _24("24", "Model charges"),
        _25("25", "Risk commission"),
        _26("26", "Guarantee commission"),
        _27("27", "Reimbursement commission"),
        _28("28", "Stamp duty"),
        _29("29", "Brokerage"),
        _30("30", "Bank charges"),
        _31("31", " Bank charges information"),
        _32("32", "Courier fee"),
        _33("33", "Phone fee"),
        _34("34", "Postage fee"),
        _35("35", "S.W.I.F.T. fee"),
        _36("36", "Telex fee"),
        _37("37", "Penalty for late delivery of documents"),
        _38("38", "Penalty for late delivery of valuation of works"),
        _39("39", "Penalty for execution of works behind schedule"),
        _40("40", "Other penalties"),
        _41("41", "Bonus for works ahead of schedule"),
        _42("42", "Other bonus"),
        _44("44", "Project management cost"),
        _45("45", "Pro rata retention"),
        _46("46", "Contractual retention"),
        _47("47", "Other retentions"),
        _48("48", "Interest on arrears"),
        _49("49", "Interest"),
        _50("50", "Charge per credit cover"),
        _51("51", "Charge per unused credit cover"),
        _52("52", "Minimum commission"),
        _53("53", "Factoring commission"),
        _54("54", "Chamber of commerce charge"),
        _55("55", "Transfer charges"),
        _56("56", "Repatriation charges"),
        _57("57", "Miscellaneous charges"),
        _58("58", "Foreign exchange charges"),
        _59("59", "Agreed debit interest charge"),
        _60("60", "Manufacturer's consumer discount"),
        _61("61", "Fax advice charge"),
        _62("62", "Due to military status"),
        _63("63", "Due to work accident"),
        _64("64", "Special agreement"),
        _65("65", "Production error discount"),
        _66("66", "New outlet discount"),
        _67("67", "Sample discount"),
        _68("68", "End-of-range discount"),
        _69("69", "Charge for a customer specific finish"),
        _70("70", "Incoterm discount"),
        _71("71", "Point of sales threshold allowance"),
        _72("72", "Technical modification costs"),
        _73("73", "Job-order production costs"),
        _74("74", "Off-premises costs"),
        _75("75", "Additional processing costs"),
        _76("76", "Attesting charge"),
        _77("77", "Rush delivery surcharge"),
        _78("78", "Special construction costs"),
        _79("79", "Freight charges"),
        _80("80", "Packing charge"),
        _81("81", "Repair charge"),
        _82("82", "Loading charge"),
        _83("83", "Setup charge"),
        _84("84", "Testing charge"),
        _85("85", "Warehousing charge"),
        _86("86", "Gold surcharge"),
        _87("87", "Copper surcharge"),
        _88("88", "Material surcharge/deduction"),
        _89("89", "Lead surcharge"),
        _90("90", "Price index surcharge"),
        _91("91", "Platinum surcharge"),
        _92("92", "Silver surcharge"),
        _93("93", "Wolfram surcharge"),
        _94("94", "Aluminum surcharge"),
        _95("95", "Discount"),
        _96("96", "Insurance"),
        _97("97", "Minimum order / minimum billing charge"),
        _98("98", "Material surcharge (special materials)"),
        _99("99", "Surcharge"),
        _100("100", "Special rebate"),
        _101("101", "Carbon footprint charge"),
        _102("102", "Fixed long term"),
        _103("103", "Temporary"),
        _104("104", "Standard"),
        _105("105", "Yearly turnover");

        private final String code;
        private final String reason;


        Allowance(final String code, final String reason) {
            this.code = code;
            this.reason = reason;

        }

        @Override
        public String groupName() {
            return "Allowance";
        }

        @Override
        public String code() {
            return this.code;
        }

        @Override
        public String getReason() {
            return this.reason;
        }
    }
    public enum Charge implements AllowanceChargeReasonCode {
        AA("Advertising"),
        AAA("Telecommunication"),
        AAC("Technical modification"),
        AAD("Job-order production"),
        AAE("Outlays"),
        AAF("Off-premises"),
        AAH("Additional processing"),
        AAI("Attesting"),
        AAS("Acceptance"),
        AAT("Rush delivery"),
        AAV("Special construction"),
        AAY("Airport facilities"),
        AAZ("Concession"),
        ABA("Compulsory storage"),
        ABB("Fuel removal"),
        ABC("Into plane"),
        ABD("Overtime"),
        ABF("Tooling"),
        ABK("Miscellaneous"),
        ABL("Additional packaging"),
        ABN("Dunnage"),
        ABR("Containerisation"),
        ABS("Carton packing"),
        ABT("Hessian wrapped"),
        ABU("Polyethylene wrap packing"),
        ACF("Miscellaneous treatment"),
        ACG("Enamelling treatment"),
        ACH("Heat treatment"),
        ACI("Plating treatment"),
        ACJ("Painting"),
        ACK("Polishing"),
        ACL("Priming"),
        ACM("Preservation treatment"),
        ACS("Fitting"),
        ADC("Consolidation"),
        ADE("Bill of lading"),
        ADJ("Airbag"),
        ADK("Transfer"),
        ADL("Slipsheet"),
        ADM("Binding"),
        ADN("Repair or replacement of broken returnable package"),
        ADO("Efficient logistics"),
        ADP("Merchandising"),
        ADQ("Product mix"),
        ADR("Other services"),
        ADT("Pick-up"),
        ADW("Chronic illness"),
        ADY("New product introduction"),
        ADZ("Direct delivery"),
        AEA("Diversion"),
        AEB("Disconnect"),
        AEC("Distribution"),
        AED("Handling of hazardous cargo"),
        AEF("Rents and leases"),
        AEH("Location differential"),
        AEI("Aircraft refueling"),
        AEJ("Fuel shipped into storage"),
        AEK("Cash on delivery"),
        AEL("Small order processing service"),
        AEM("Clerical or administrative services"),
        AEN("Guarantee"),
        AEO("Collection and recycling"),
        AEP("Copyright fee collection"),
        AES("Veterinary inspection service"),
        AET("Pensioner service"),
        AEU("Medicine free pass holder"),
        AEV("Environmental protection service"),
        AEW("Environmental clean-up service"),
        AEX("National cheque processing service outside account area"),
        AEY("National payment service outside account area"),
        AEZ("National payment service within account area"),
        AJ("Adjustments"),
        AU("Authentication"),
        CA("Cataloguing"),
        CAB("Cartage"),
        CAD("Certification"),
        CAE("Certificate of conformance"),
        CAF("Certificate of origin"),
        CAI("Cutting"),
        CAJ("Consular service"),
        CAK("Customer collection"),
        CAL("Payroll payment service"),
        CAM("Cash transportation"),
        CAN("Home banking service"),
        CAO("Bilateral agreement service"),
        CAP("Insurance brokerage service"),
        CAQ("Cheque generation"),
        CAR("Preferential merchandising location"),
        CAS("Crane"),
        CAT("Special colour service"),
        CAU("Sorting"),
        CAV("Battery collection and recycling"),
        CAW("Product take back fee"),
        CD("Car loading"),
        CG("Cleaning"),
        CS("Cigarette stamping"),
        CT("Count and recount"),
        DAB("Layout/design"),
        DAD("Driver assigned unloading"),
        DL("Delivery"),
        EG("Engraving"),
        EP("Expediting"),
        ER("Exchange rate guarantee"),
        FAA("Fabrication"),
        FAB("Freight equalization"),
        FAC("Freight extraordinary handling"),
        FC("Freight service"),
        FH("Filling/handling"),
        FI("Financing"),
        GAA("Grinding"),
        HAA("Hose"),
        HD("Handling"),
        HH("Hoisting and hauling"),
        IAA("Installation"),
        IAB("Installation and warranty"),
        ID("Inside delivery"),
        IF("Inspection"),
        IR("Installation and training"),
        IS("Invoicing"),
        KO("Koshering"),
        L1("Carrier count"),
        LA("Labelling"),
        LAA("Labour"),
        LAB("Repair and return"),
        LF("Legalisation"),
        MAE("Mounting"),
        MI("Mail invoice"),
        ML("Mail invoice to each location"),
        NAA("Non-returnable containers"),
        OA("Outside cable connectors"),
        PA("Invoice with shipment"),
        PAA("Phosphatizing (steel treatment)"),
        PC("Packing"),
        PL("Palletizing"),
        RAB("Repacking"),
        RAC("Repair"),
        RAD("Returnable container"),
        RAF("Restocking"),
        RE("Re-delivery"),
        RF("Refurbishing"),
        RH("Rail wagon hire"),
        RV("Loading"),
        SA("Salvaging"),
        SAA("Shipping and handling"),
        SAD("Special packaging"),
        SAE("Stamping"),
        SAI("Consignee unload"),
        SG("Shrink-wrap"),
        SH("Special handling"),
        SM("Special finish"),
        SU("Set-up"),
        TAB("Tank renting"),
        TAC("Testing"),
        TT("Transportation - third party billing"),
        TV("Transportation by vendor"),
        V1("Drop yard"),
        V2("Drop dock"),
        WH("Warehousing"),
        XAA("Combine all same day shipment"),
        YY("Split pick-up"),
        ZZZ("Mutually defined");

        private final String reason;
        private final String code;

        Charge(String reason) {
            this.reason = reason;
            this.code = this.toString();

        }

        @Override
        public String groupName() {
            return "Charge";
        }

        @Override
        public String code() {
            return this.code;
        }

        @Override
        public String getReason() {
            return this.reason;
        }
    }
}
